# PRAKTIKUM PENAMBANGAN DATA (PPD)
## MODUL 1: NUMPY DAN PANDAS

* **Nama**: Januarsyah
* **Mata Kuliah**: Praktikum Penambangan Data (SVPL214610)
* **Program Studi**: D4 Teknologi Rekayasa Perangkat Lunak, Sekolah Vokasi UGM

---

### 0. Environment Setup
Cell ini menginisialisasi pustaka utama (`NumPy` dan `Pandas`) serta memeriksa versi pustaka yang digunakan.

In [15]:
import numpy as np
import pandas as pd

print(f"NumPy Version : {np.__version__}")
print(f"Pandas Version: {pd.__version__}")

NumPy Version : 2.0.2
Pandas Version: 2.2.3

---
# 1. LANGKAH PERCOBAAN: NUMPY

NumPy (*Numerical Python*) adalah pustaka fundamental untuk komputasi numerik di Python dengan struktur data utama berupa **ndarray** (N-dimensional array).

#### 1.1 Pembuatan Array 1D, 2D, dan 3D beserta Pengecekan `.shape`

In [16]:
# Array 1 Dimensi
arr1d = np.array([1, 2, 3, 4, 5])
print("Array 1D:", arr1d)
print("Shape 1D:", arr1d.shape)
print("Tipe Data:", type(arr1d))
print("-" * 30)

# Array 2 Dimensi (2 baris, 3 kolom)
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print("Array 2D:")
print(arr2d)
print("Shape 2D:", arr2d.shape)
print("-" * 30)

# Array 3 Dimensi (3 blok, 2 baris, 4 kolom)
arr3d = np.array([
    [[1, 2, 3, 4], [5, 6, 7, 8]],
    [[9, 10, 11, 12], [13, 14, 15, 16]],
    [[17, 18, 19, 20], [21, 22, 23, 24]]
])
print("Array 3D:")
print(arr3d)
print("Shape 3D:", arr3d.shape)

Array 1D: [1 2 3 4 5]
Shape 1D: (5,)
Tipe Data: <class 'numpy.ndarray'>
------------------------------
Array 2D:
[[1 2 3]
 [4 5 6]]
Shape 2D: (2, 3)
------------------------------
Array 3D:
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]
Shape 3D: (3, 2, 4)

#### 1.2 Indexing dan Slicing Array Multidimensi

In [17]:
# Indexing 1D & 2D
print("Elemen ke-0 arr1d:", arr1d[0])
print("Elemen baris 0 kolom 1 arr2d:", arr2d[0, 1])
print("Elemen blok 1 baris 1 kolom 2 arr3d:", arr3d[1, 1, 2])

# Slicing Array
print("\nSlicing arr1d (indeks 1 sampai 3):", arr1d[1:4])
print("Slicing arr2d (semua baris, kolom 1-2):")
print(arr2d[:, 1:])

Elemen ke-0 arr1d: 1
Elemen baris 0 kolom 1 arr2d: 2
Elemen blok 1 baris 1 kolom 2 arr3d: 15

Slicing arr1d (indeks 1 sampai 3): [2 3 4]
Slicing arr2d (semua baris, kolom 1-2):
[[2 3]
 [5 6]]

#### 1.3 Pembuatan Array dengan Helper Functions (zeros, ones, arange, linspace, eye)

In [18]:
print("Zeros (2x3):")
print(np.zeros((2, 3)))
print("\nOnes (2x2):")
print(np.ones((2, 2)))
print("\nArange (0 sampai 10 kelipatan 2):", np.arange(0, 10, 2))
print("\nLinspace (0 sampai 1 dibagi 5 titik):", np.linspace(0, 1, 5))
print("\nEye / Matriks Identitas (3x3):")
print(np.eye(3))

Zeros (2x3):
[[0. 0. 0.]
 [0. 0. 0.]]

Ones (2x2):
[[1. 1.]
 [1. 1.]]

Arange (0 sampai 10 kelipatan 2): [0 2 4 6 8]

Linspace (0 sampai 1 dibagi 5 titik): [0.   0.25 0.5  0.75 1.  ]

Eye / Matriks Identitas (3x3):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

#### 1.4 Reshape dan Konversi Tipe Data

In [19]:
data = np.arange(1, 13)
print("Data awal (1D):", data)

# Reshape ke 3x4
reshaped_3x4 = data.reshape(3, 4)
print("\nReshape ke (3, 4):")
print(reshaped_3x4)

# Reshape kembali ke 1D (-1 atau flatten)
flattened = reshaped_3x4.reshape(-1)
print("\nKembali ke 1D:", flattened)

# Konversi Tipe Data
arr_float = data.astype(float)
print("\nKonversi ke Float:", arr_float)
print("Tipe data element:", arr_float.dtype)

Data awal (1D): [ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshape ke (3, 4):
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Kembali ke 1D: [ 1  2  3  4  5  6  7  8  9 10 11 12]

Konversi ke Float: [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]
Tipe data element: float64

#### 1.5 Operasi Array (Join, Split, Search, Sort, Random, dan Matematika)

In [20]:
# Concatenate / Join
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("Join 1D:", np.concatenate((a, b)))

# NumPy Random
np.random.seed(42)
random_arr = np.random.randint(0, 100, size=(3, 3))
print("\nArray Random (3x3):")
print(random_arr)

# Search dengan np.where
indices = np.where(random_arr > 50)
print("\nIndeks elemen > 50:", indices)
print("Nilai elemen > 50:", random_arr[indices])

# Sorting
print("\nSorted array (per baris):")
print(np.sort(random_arr, axis=1))

# Operasi Statistik / Matematika
print("\nTotal Sum:", np.sum(random_arr))
print("Sum per Kolom (axis 0):", np.sum(random_arr, axis=0))
print("Mean / Rata-rata:", np.mean(random_arr))

Join 1D: [1 2 3 4 5 6]

Array Random (3x3):
[[51 92 14]
 [71 60 20]
 [82 86 74]]

Indeks elemen > 50: (array([0, 0, 1, 1, 2, 2, 2]), array([0, 1, 0, 1, 0, 1, 2]))
Nilai elemen > 50: [51 92 71 60 82 86 74]

Sorted array (per baris):
[[14 51 92]
 [20 60 71]
 [74 82 86]]

Total Sum: 550
Sum per Kolom (axis 0): [204 238 108]
Mean / Rata-rata: 61.111111111111114

---
# 2. LANGKAH PERCOBAAN: PANDAS

Pandas menyediakan struktur data **DataFrame** (2D) dan **Series** (1D) yang sangat fleksibel untuk manipulasi dan analisis data tabular.

#### 2.1 Pembuatan DataFrame, Penambahan & Penghapusan Kolom

In [21]:
# Membuat DataFrame awal
data_mhs = {
    'NIM': ['22/001', '22/002', '22/003', '22/004'],
    'Nama': ['Budi', 'Siti', 'Joko', 'Dewi'],
    'Jurusan': ['TRPL', 'TRPL', 'TRK', 'TRPL'],
    'Nilai_UAS': [85, 92, 78, 88]
}
df_mhs = pd.DataFrame(data_mhs)
print("DataFrame Awal:")
display(df_mhs)

# Menambahkan Kolom Baru
df_mhs['Status'] = ['Lulus', 'Lulus', 'Lulus', 'Lulus']
df_mhs['Nilai_Akhir'] = df_mhs['Nilai_UAS'] + 5
print("\nSetelah Menambah Kolom:")
display(df_mhs)

# Menghapus Kolom
df_clean = df_mhs.drop(columns=['Status'])
print("\nSetelah Menghapus Kolom Status:")
display(df_clean)

DataFrame Awal:

      NIM  Nama Jurusan  Nilai_UAS
0  22/001  Budi    TRPL         85
1  22/002  Siti    TRPL         92
2  22/003  Joko     TRK         78
3  22/004  Dewi    TRPL         88

Setelah Menambah Kolom:

      NIM  Nama Jurusan  Nilai_UAS Status  Nilai_Akhir
0  22/001  Budi    TRPL         85  Lulus           90
1  22/002  Siti    TRPL         92  Lulus           97
2  22/003  Joko     TRK         78  Lulus           83
3  22/004  Dewi    TRPL         88  Lulus           93

Setelah Menghapus Kolom Status:

      NIM  Nama Jurusan  Nilai_UAS  Nilai_Akhir
0  22/001  Budi    TRPL         85           90
1  22/002  Siti    TRPL         92           97
2  22/003  Joko     TRK         78           83
3  22/004  Dewi    TRPL         88           93

#### 2.2 Sorting dan Filtering Data

In [22]:
# Filtering: Nilai_UAS >= 85 dan Jurusan TRPL
filtered_df = df_mhs[(df_mhs['Nilai_UAS'] >= 85) & (df_mhs['Jurusan'] == 'TRPL')]
print("Hasil Filtering:")
display(filtered_df)

# Sorting berdasarkan Nilai_UAS secara Descending
sorted_df = df_mhs.sort_values(by='Nilai_UAS', ascending=False)
print("\nHasil Sorting:")
display(sorted_df)

Hasil Filtering:

      NIM  Nama Jurusan  Nilai_UAS Status  Nilai_Akhir
0  22/001  Budi    TRPL         85  Lulus           90
1  22/002  Siti    TRPL         92  Lulus           97
3  22/004  Dewi    TRPL         88  Lulus           93

Hasil Sorting:

      NIM  Nama Jurusan  Nilai_UAS Status  Nilai_Akhir
1  22/002  Siti    TRPL         92  Lulus           97
3  22/004  Dewi    TRPL         88  Lulus           93
0  22/001  Budi    TRPL         85  Lulus           90
2  22/003  Joko     TRK         78  Lulus           83

#### 2.3 Grouping dan Aggregation (`groupby` & `agg`)

In [23]:
# Data Karyawan
data_karyawan = {
    'Nama': ['Budi', 'Maya', 'Joko', 'Andi', 'Dewi', 'Dian'],
    'Gender': ['Pria', 'Perempuan', 'Pria', 'Pria', 'Perempuan', 'Perempuan'],
    'Pekerjaan': ['Programmer', 'Programmer', 'Data Engineer', 'Manager', 'Manager', 'Manager'],
    'Gaji': [5000, 5200, 4500, 6500, 8000, 6200],
    'Pengalaman_Th': [2, 3, 1, 5, 7, 4]
}
df_emp = pd.DataFrame(data_karyawan)
display(df_emp)

# Groupby Pekerjaan dengan multiple agregasi
agg_result = df_emp.groupby('Pekerjaan').agg(
    Jumlah_Pegawai=('Nama', 'count'),
    Rata_Gaji=('Gaji', 'mean'),
    Total_Gaji=('Gaji', 'sum'),
    Max_Pengalaman=('Pengalaman_Th', 'max')
).reset_index()

print("\nHasil Groupby & Aggregation:")
display(agg_result)

   Nama     Gender      Pekerjaan  Gaji  Pengalaman_Th
0  Budi       Pria     Programmer  5000              2
1  Maya  Perempuan     Programmer  5200              3
2  Joko       Pria  Data Engineer  4500              1
3  Andi       Pria        Manager  6500              5
4  Dewi  Perempuan        Manager  8000              7
5  Dian  Perempuan        Manager  6200              4

Hasil Groupby & Aggregation:

       Pekerjaan  Jumlah_Pegawai  Rata_Gaji  Total_Gaji  Max_Pengalaman
0  Data Engineer               1     4500.0        4500               1
1        Manager               3     6900.0       20700               7
2     Programmer               2     5100.0       10200               3

#### 2.4 Penggabungan Data: `merge`, `join`, dan `concat`

In [24]:
# DataFrame 1
df_karyawan = pd.DataFrame({
    'Emp_id': ['E01', 'E02', 'E03'],
    'Nama': ['Budi', 'Joko', 'Maya'],
    'Id_Dept': [1, 2, 1]
})

# DataFrame 2
df_dept = pd.DataFrame({
    'Id_Dept': [1, 2, 3],
    'Nama_Dept': ['IT Solution', 'Data Analytics', 'Finance']
})

# Merge (Inner & Left)
merged_df = pd.merge(df_karyawan, df_dept, on='Id_Dept', how='left')
print("Hasil Merge (Left Join):")
display(merged_df)

# Concat baris (axis=0)
df_baru = pd.DataFrame({
    'Emp_id': ['E04'],
    'Nama': ['Rina'],
    'Id_Dept': [3]
})
all_karyawan = pd.concat([df_karyawan, df_baru], ignore_index=True)
print("\nHasil Concat Baris:")
display(all_karyawan)

Hasil Merge (Left Join):

  Emp_id  Nama  Id_Dept       Nama_Dept
0    E01  Budi        1     IT Solution
1    E02  Joko        2  Data Analytics
2    E03  Maya        1     IT Solution

Hasil Concat Baris:

  Emp_id  Nama  Id_Dept
0    E01  Budi        1
1    E02  Joko        2
2    E03  Maya        1
3    E04  Rina        3

#### 2.5 Reshaping Data: `pivot_table`, `melt`, dan `apply(lambda)`

In [25]:
# Pivot Table
pivot = pd.pivot_table(df_emp, values='Gaji', index='Pekerjaan', columns='Gender', aggfunc='mean')
print("Pivot Table (Rata-rata Gaji per Pekerjaan & Gender):")
display(pivot)

# Melt (Wide to Long)
scores = pd.DataFrame({
    'Nama': ['Ali', 'Budi'],
    'Matematika': [80, 90],
    'Fisika': [85, 75]
})
melted = pd.melt(scores, id_vars=['Nama'], value_vars=['Matematika', 'Fisika'], var_name='Mata_Pelajaran', value_name='Nilai')
print("\nHasil Melt (Format Panjang):")
display(melted)

# Lambda Function dengan Apply
df_emp['Kategori_Gaji'] = df_emp['Gaji'].apply(lambda x: 'Tinggi' if x >= 6000 else ('Sedang' if x >= 5000 else 'Standar'))
print("\nSetelah Apply Lambda Kategori Gaji:")
display(df_emp[['Nama', 'Pekerjaan', 'Gaji', 'Kategori_Gaji']])

Pivot Table (Rata-rata Gaji per Pekerjaan & Gender):

Gender         Perempuan    Pria
Pekerjaan
Data Engineer        NaN  4500.0
Manager           7100.0  6500.0
Programmer        5200.0  5000.0

Hasil Melt (Format Panjang):

   Nama Mata_Pelajaran  Nilai
0   Ali     Matematika     80
1  Budi     Matematika     90
2   Ali         Fisika     85
3  Budi         Fisika     75

Setelah Apply Lambda Kategori Gaji:

   Nama      Pekerjaan  Gaji Kategori_Gaji
0  Budi     Programmer  5000        Sedang
1  Maya     Programmer  5200        Sedang
2  Joko  Data Engineer  4500       Standar
3  Andi        Manager  6500        Tinggi
4  Dewi        Manager  8000        Tinggi
5  Dian        Manager  6200        Tinggi

---
# 3. TUGAS & ANALISIS (BAB 1.5)

Bagian ini berisi penyelesaian lengkap dari ketiga soal tugas praktikum pertemuan 1 beserta penjelasannya.

### Soal 1: NumPy Reshape & Filtering
> **Deskripsi Tugas:**
> Buatlah array NumPy 2D berukuran $4\times4$ berisi angka acak (rentang 0–50), kemudian ubah bentuknya (*reshape*) menjadi array $2\times8$ dan tampilkan hanya elemen-elemen yang bernilai lebih dari 25.

In [26]:
# 1. Membuat array 2D 4x4 berisi integer acak 0-50
np.random.seed(42) # Seed untuk reproduktibilitas
arr_soal1 = np.random.randint(0, 51, size=(4, 4))
print("1. Array 2D Asal (4x4):")
print(arr_soal1)
print("   Shape:", arr_soal1.shape)
print("-" * 40)

# 2. Reshape array menjadi 2x8
arr_reshaped = arr_soal1.reshape(2, 8)
print("2. Hasil Reshape (2x8):")
print(arr_reshaped)
print("   Shape:", arr_reshaped.shape)
print("-" * 40)

# 3. Filter dan tampilkan hanya elemen yang > 25
elemen_gt_25 = arr_reshaped[arr_reshaped > 25]
print("3. Elemen-elemen yang bernilai > 25:")
print(elemen_gt_25)
print("   Banyaknya elemen yang memenuhi:", len(elemen_gt_25))

1. Array 2D Asal (4x4):
[[38 28 14 42]
 [ 7 20 38 18]
 [22 10 10 23]
 [35 39 23  2]]
   Shape: (4, 4)
----------------------------------------
2. Hasil Reshape (2x8):
[[38 28 14 42  7 20 38 18]
 [22 10 10 23 35 39 23  2]]
   Shape: (2, 8)
----------------------------------------
3. Elemen-elemen yang bernilai > 25:
[38 28 42 38 35 39]
   Banyaknya elemen yang memenuhi: 6

**Penjelasan / Analisis Soal 1:**
1. `np.random.randint(0, 51, size=(4, 4))` menghasilkan 16 angka acak bulat dalam rentang interval tertutup $[0, 50]$ dalam matriks 2D berdimensi $(4, 4)$.
2. Fungsi `.reshape(2, 8)` menata ulang 16 elemen tersebut menjadi matriks baru berdimensi $(2, 8)$ tanpa mengubah susunan data dasarnya dalam memori.
3. Operasi boolean indexing `arr_reshaped[arr_reshaped > 25]` melakukan filtering kondisi elemen secara tervektorisasi (*vectorized comparison*), menghasilkan array 1D yang hanya berisi nilai-nilai di atas 25.

---
### Soal 2: Pandas Groupby & Multiple Aggregations
> **Deskripsi Tugas:**
> Buatlah DataFrame untuk data karyawan yang berisi kolom `Nama`, `Pekerjaan`, dan `Gaji`. Lalu lakukan operasi `groupby()` pada kolom `Pekerjaan` dan hitung nilai **maksimum**, **minimum**, serta **standar deviasi** untuk kolom `Gaji` menggunakan `agg()`.

In [27]:
# 1. Membuat DataFrame data karyawan
data_soal2 = {
    'Nama': ['Andi', 'Budi', 'Citra', 'Dewi', 'Eko', 'Fani', 'Gita', 'Hadi'],
    'Pekerjaan': ['Programmer', 'Programmer', 'Data Analyst', 'Data Analyst', 'Manager', 'Manager', 'Programmer', 'Data Analyst'],
    'Gaji': [6000000, 6500000, 5500000, 5800000, 9500000, 10000000, 7000000, 6200000]
}

df_karyawan_soal2 = pd.DataFrame(data_soal2)
print("Data Karyawan:")
display(df_karyawan_soal2)
print("-" * 50)

# 2. Operasi groupby() dan agg() untuk Max, Min, dan Std Deviasi kolom Gaji
hasil_agg = df_karyawan_soal2.groupby('Pekerjaan')['Gaji'].agg(
    Gaji_Maksimum='max',
    Gaji_Minimum='min',
    Standar_Deviasi='std'
).reset_index()

print("\nHasil Agregasi Gaji per Pekerjaan:")
display(hasil_agg)

Data Karyawan:

    Nama     Pekerjaan      Gaji
0   Andi    Programmer   6000000
1   Budi    Programmer   6500000
2  Citra  Data Analyst   5500000
3   Dewi  Data Analyst   5800000
4    Eko       Manager   9500000
5   Fani       Manager  10000000
6   Gita    Programmer   7000000
7   Hadi  Data Analyst   6200000

--------------------------------------------------

Hasil Agregasi Gaji per Pekerjaan:

      Pekerjaan  Gaji_Maksimum  Gaji_Minimum  Standar_Deviasi
0  Data Analyst        6200000       5500000    351188.458428
1       Manager       10000000       9500000    353553.390593
2    Programmer        7000000       6000000    500000.000000

**Penjelasan / Analisis Soal 2:**
1. Metode `df.groupby('Pekerjaan')` mengelompokkan data baris berdasarkan kategori unik yang ada pada kolom `Pekerjaan` (`Data Analyst`, `Manager`, `Programmer`).
2. Dengan mengarahkan seleksi ke kolom `['Gaji']` dan menerapkan `.agg(...)`, kita dapat menghitung metrik statistik deskriptif secara spesifik:
   - `max`: nilai gaji tertinggi pada setiap kelompok jabatan.
   - `min`: nilai gaji terendah pada setiap kelompok jabatan.
   - `std`: standar deviasi gaji yang mengukur sebaran atau variasi besaran gaji antar karyawan dalam satu jabatan.
3. `.reset_index()` digunakan agar hasil kelompok diubah kembali menjadi kolom reguler DataFrame sehingga mudah dibaca dan dianalisis lebih lanjut.

---
### Soal 3: Pandas Merge (Left Join dengan Key Berbeda & Suffixes)
> **Deskripsi Tugas:**
> Buat dua DataFrame untuk data karyawan dengan kolom `Emp_id`, `Nama`, dan `Divisi`, serta DataFrame gaji dengan kolom `ID`, `Gaji`, dan `Status` (masing-masing minimal tiga baris). Setelah itu, gabungkan kedua DataFrame tersebut menggunakan `merge()` dengan `left_on='Emp_id'` dan `right_on='ID'`, terapkan **left join**, dan gunakan `suffixes` untuk membedakan kolom yang sama.

In [28]:
# 1. Membuat DataFrame Karyawan (Tabel Kiri)
df_info_karyawan = pd.DataFrame({
    'Emp_id': ['EMP01', 'EMP02', 'EMP03', 'EMP04'],
    'Nama': ['Rian', 'Sari', 'Doni', 'Lestari'],
    'Divisi': ['Engineering', 'Data Science', 'Product', 'Marketing'],
    'Status': ['Aktif', 'Aktif', 'Cuti', 'Aktif'] # Kolom Status di tabel kiri
})

# 2. Membuat DataFrame Gaji (Tabel Kanan)
df_gaji_karyawan = pd.DataFrame({
    'ID': ['EMP01', 'EMP02', 'EMP03', 'EMP05'], # EMP04 tidak ada di kanan, EMP05 tidak ada di kiri
    'Gaji': [7500000, 8200000, 6800000, 9000000],
    'Status': ['Tetap', 'Kontrak', 'Tetap', 'Kontrak'] # Kolom Status di tabel kanan
})

print("DataFrame Karyawan (Kiri):")
display(df_info_karyawan)
print("\nDataFrame Gaji (Kanan):")
display(df_gaji_karyawan)
print("-" * 60)

# 3. Menggabungkan kedua DataFrame menggunakan merge (Left Join, left_on, right_on, suffixes)
df_merged = pd.merge(
    df_info_karyawan,
    df_gaji_karyawan,
    left_on='Emp_id',
    right_on='ID',
    how='left',
    suffixes=('_karyawan', '_kepegawaian')
)

print("\nHasil Merge (Left Join):")
display(df_merged)

DataFrame Karyawan (Kiri):

  Emp_id     Nama        Divisi Status
0  EMP01     Rian   Engineering  Aktif
1  EMP02     Sari  Data Science  Aktif
2  EMP03     Doni       Product   Cuti
3  EMP04  Lestari     Marketing  Aktif

DataFrame Gaji (Kanan):

      ID     Gaji   Status
0  EMP01  7500000    Tetap
1  EMP02  8200000  Kontrak
2  EMP03  6800000    Tetap
3  EMP05  9000000  Kontrak

------------------------------------------------------------

Hasil Merge (Left Join):

,Emp_id,Nama,Divisi,Status_karyawan,ID,Gaji,Status_kepegawaian
0,EMP01,Rian,Engineering,Aktif,EMP01,7500000.0,Tetap
1,EMP02,Sari,Data Science,Aktif,EMP02,8200000.0,Kontrak
2,EMP03,Doni,Product,Cuti,EMP03,6800000.0,Tetap
3,EMP04,Lestari,Marketing,Aktif,NaN,NaN,NaN

**Penjelasan / Analisis Soal 3:**
1. **Left Join (`how='left'`)**: Mempertahankan seluruh entri dari DataFrame kiri (`df_info_karyawan`). Untuk baris karyawan `EMP04` yang tidak memiliki pasangan id di tabel kanan (`df_gaji_karyawan`), nilai kolom `Gaji` dan `Status` dari tabel kanan akan otomatis diisi dengan `NaN` (*Not a Number*).
2. **Kunci Penghubung (`left_on` & `right_on`)**: Karena nama kolom identitas berbeda di kedua tabel (`Emp_id` vs `ID`), parameter `left_on='Emp_id'` dan `right_on='ID'` digunakan untuk memetakan kesamaan nilai kunci.
3. **Parameter `suffixes`**: Kolom `Status` yang terdapat di kedua DataFrame secara otomatis dibedakan namanya menjadi `Status_karyawan` dan `Status_kepegawaian`, sehingga menghindari ambiguasi nama kolom (*column name collision*).